In [25]:
import tensorflow as tf

sess = tf.InteractiveSession()

i_matrix = tf.eye(5)
"i_matrix:"
i_matrix.eval()

X = tf.Variable(tf.eye(10))
X.initializer.run()
'X:'
X.eval()

A = tf.Variable(tf.random_normal([5, 10]))
A.initializer.run()
'A:'
A.eval()

product = tf.matmul(A, X)
"product"
product.eval()

b = tf.Variable(tf.random_uniform([5, 10], 0, 2, dtype=tf.int32))
b.initializer.run()
"b:"
b.eval()

b_new = tf.cast(b, dtype=tf.float32)
"b_new: "
b_new.eval()

t_sum = tf.add(product, b_new)
t_sub = product - b_new

't_sum: '
t_sum.eval()
't_sub: '
t_sub.eval()


'i_matrix:'

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)

'X:'

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

'A:'

array([[ 1.2374613 , -0.2098737 ,  0.4506511 , -0.5405326 , -0.7613381 ,
        -0.905467  , -0.64189035, -0.79836965,  0.92737055, -0.17159584],
       [-0.24566267,  0.01555847, -0.89134794,  0.43484715,  0.4207015 ,
        -1.8845923 , -0.8731752 ,  0.03129596,  0.44302005,  0.80899763],
       [ 1.1075478 , -1.2655593 , -0.20941381,  0.68105704,  0.53564304,
        -0.4606952 , -0.5105552 ,  0.95899665, -0.3704556 , -0.25007647],
       [ 0.11618522, -0.7288683 ,  0.5816725 ,  2.200534  ,  1.4602734 ,
        -0.4465991 ,  0.51959443,  1.1336328 ,  0.67163306, -0.5108663 ],
       [ 0.4470835 ,  1.1441895 , -0.8682258 , -1.4902253 ,  0.549852  ,
        -0.11187275, -1.4478278 , -1.6417572 ,  1.4259431 ,  0.2157852 ]],
      dtype=float32)

'product'

array([[ 1.2374613 , -0.2098737 ,  0.4506511 , -0.5405326 , -0.7613381 ,
        -0.905467  , -0.64189035, -0.79836965,  0.92737055, -0.17159584],
       [-0.24566267,  0.01555847, -0.89134794,  0.43484715,  0.4207015 ,
        -1.8845923 , -0.8731752 ,  0.03129596,  0.44302005,  0.80899763],
       [ 1.1075478 , -1.2655593 , -0.20941381,  0.68105704,  0.53564304,
        -0.4606952 , -0.5105552 ,  0.95899665, -0.3704556 , -0.25007647],
       [ 0.11618522, -0.7288683 ,  0.5816725 ,  2.200534  ,  1.4602734 ,
        -0.4465991 ,  0.51959443,  1.1336328 ,  0.67163306, -0.5108663 ],
       [ 0.4470835 ,  1.1441895 , -0.8682258 , -1.4902253 ,  0.549852  ,
        -0.11187275, -1.4478278 , -1.6417572 ,  1.4259431 ,  0.2157852 ]],
      dtype=float32)

'b:'

array([[1, 1, 0, 1, 0, 1, 1, 1, 0, 1],
       [1, 1, 1, 0, 0, 1, 1, 0, 0, 0],
       [1, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 1, 0, 0, 1, 1, 1, 0, 0]])

'b_new: '

array([[1., 1., 0., 1., 0., 1., 1., 1., 0., 1.],
       [1., 1., 1., 0., 0., 1., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 1., 0., 0., 1., 1., 1., 0., 0.]], dtype=float32)

't_sum: '

array([[ 2.2374613 ,  0.7901263 ,  0.4506511 ,  0.4594674 , -0.7613381 ,
         0.09453303,  0.35810965,  0.20163035,  0.92737055,  0.8284042 ],
       [ 0.7543373 ,  1.0155585 ,  0.10865206,  0.43484715,  0.4207015 ,
        -0.8845923 ,  0.1268248 ,  0.03129596,  0.44302005,  0.80899763],
       [ 2.1075478 , -0.26555932, -0.20941381,  1.681057  ,  0.53564304,
         0.5393048 , -0.5105552 ,  1.9589967 , -0.3704556 ,  0.7499235 ],
       [ 0.11618522, -0.7288683 ,  1.5816724 ,  2.200534  ,  1.4602734 ,
        -0.4465991 ,  0.51959443,  1.1336328 ,  1.671633  ,  0.48913372],
       [ 0.4470835 ,  1.1441895 ,  0.13177419, -1.4902253 ,  0.549852  ,
         0.88812727, -0.44782782, -0.64175725,  1.4259431 ,  0.2157852 ]],
      dtype=float32)

't_sub: '

array([[ 0.23746133, -1.2098737 ,  0.4506511 , -1.5405326 , -0.7613381 ,
        -1.905467  , -1.6418903 , -1.7983696 ,  0.92737055, -1.1715958 ],
       [-1.2456627 , -0.9844415 , -1.8913479 ,  0.43484715,  0.4207015 ,
        -2.8845923 , -1.8731751 ,  0.03129596,  0.44302005,  0.80899763],
       [ 0.10754776, -2.2655592 , -0.20941381, -0.31894296,  0.53564304,
        -1.4606953 , -0.5105552 , -0.04100335, -0.3704556 , -1.2500765 ],
       [ 0.11618522, -0.7288683 , -0.4183275 ,  2.200534  ,  1.4602734 ,
        -0.4465991 ,  0.51959443,  1.1336328 , -0.32836694, -1.5108663 ],
       [ 0.4470835 ,  1.1441895 , -1.8682258 , -1.4902253 ,  0.549852  ,
        -1.1118728 , -2.4478278 , -2.6417572 ,  1.4259431 ,  0.2157852 ]],
      dtype=float32)