In [76]:
import numpy as np

a = np.arange(36).reshape(-1, 6)
a

a.trace()
a.diagonal()

array([ 0,  7, 14, 21, 28, 35])

In [46]:
np.hsplit(a, 2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]])]

In [47]:
np.vsplit(a, 2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [48]:
b1 = np.array([[1, 2],[3, 4]])
b2 = np.array([[7, 8],[9, 10]])

In [49]:
np.hstack((b1, b2))

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10]])

In [50]:
np.column_stack((b1, b2))

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10]])

In [51]:
np.vstack((b1, b2))

array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 9, 10]])

In [84]:
d = np.diag([1, 2, 3])
print(d)
# help(np.diag)
np.diag(d)
help(np.diag)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
Help on function diag in module numpy:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D arr

In [55]:
np.diag_indices(5)

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [62]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])