+ array
+ zeros
+ zeros_like
+ ones
+ ones_like
+ empty
+ empty_like
+ arange
+ linspace
+ numpy.random.rand
+ numpy.random.randn
+ fromfunction
+ fromfile

In [23]:
import numpy as np

In [24]:
np.ones(3)

array([1., 1., 1.])

In [25]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.empty(3)

array([1., 1., 1.])

In [27]:
np.empty((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
np.empty((3, 5, 2))

array([[[9.84486834e-312, 9.58487353e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 5.02034658e+175],
        [9.15716591e-071, 3.72472063e-057],
        [1.84835182e+184, 7.49405771e-067]],

       [[1.47763641e+248, 1.16096346e-028],
        [7.69165785e+218, 1.35617292e+248],
        [2.72955582e-057, 9.60290951e-071],
        [3.92196076e+179, 1.90221212e+185],
        [4.30695224e-096, 6.32299154e+233]],

       [[6.48224638e+170, 5.22411352e+257],
        [5.74020278e+180, 8.37174974e-144],
        [1.41529402e+161, 9.16651763e-072],
        [4.95296727e+097, 2.21624286e-052],
        [2.74550025e+126, 7.36744415e-308]]])

In [28]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [29]:
np.linspace( 0, 2, 9 )

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [32]:
np.linspace( 0, 2 * np.pi, 20 )

array([0.        , 0.33069396, 0.66138793, 0.99208189, 1.32277585,
       1.65346982, 1.98416378, 2.31485774, 2.64555171, 2.97624567,
       3.30693964, 3.6376336 , 3.96832756, 4.29902153, 4.62971549,
       4.96040945, 5.29110342, 5.62179738, 5.95249134, 6.28318531])

In [51]:
# print(dir(np.random))
# help(np.random.rand)
help(np.random.random)
# help(np.random.randn)
# help(np.random.normal)

Help on built-in function random_sample:

random_sample(...) method of mtrand.RandomState instance
    random_sample(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0).
    
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random_sample` by `(b-a)` and add `a`::
    
      (b - a) * random_sample() + a
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    out : float or ndarray of floats
        Array of random floats of shape `size` (unless ``size=None``, in which
        case a single float is returned).
    
    Examples
    --------
    >>> np.random.random_sample()
    0.47108547995356098
    >>> type(np.random.random_

In [58]:
np.random.random((2, 3, 4, 2))

array([[[[0.10408002, 0.25762659],
         [0.21154143, 0.01802592],
         [0.8308709 , 0.88655766],
         [0.10428269, 0.22385601]],

        [[0.36565354, 0.47900836],
         [0.703862  , 0.14362308],
         [0.96840437, 0.56189553],
         [0.49523705, 0.25521773]],

        [[0.38517284, 0.0817065 ],
         [0.97916659, 0.93393629],
         [0.01917451, 0.51070769],
         [0.95202403, 0.05719351]]],


       [[[0.99915583, 0.48474008],
         [0.96401556, 0.17682774],
         [0.06256103, 0.33982749],
         [0.48951153, 0.39711451]],

        [[0.1310711 , 0.81785843],
         [0.08962947, 0.83817819],
         [0.04675339, 0.64480534],
         [0.16664925, 0.9020475 ]],

        [[0.0342704 , 0.41537559],
         [0.68980495, 0.23538882],
         [0.35103365, 0.6654374 ],
         [0.53918537, 0.79582728]]]])

In [70]:
np.random.rand(2, 3, 4).mean(axis=1)

array([[0.56144248, 0.41177938, 0.56897945, 0.45079837],
       [0.22564688, 0.41603056, 0.57507191, 0.3807704 ]])

In [56]:
np.random.normal(0, 5, 10)

array([ 3.50360344,  0.70982691, -1.95942181, -4.2227694 ,  3.9211386 ,
        7.22077271,  6.74234637,  5.88578921, -1.75647294, 16.1112182 ])