In [3]:
import numpy as np

sample = np.random.randint(low=1,high=100,size=10)
sample
[np.random.choice(sample, size=sample.shape) for i in range(100)]

array([ 5, 32, 85, 81, 44, 90,  2, 96, 86, 97])

[array([44, 85, 96,  5, 97, 96, 81, 86, 86, 96]),
 array([85, 97, 44, 85, 97,  5, 32,  2, 90, 32]),
 array([96, 86, 97,  5, 97, 44, 86, 81, 97, 81]),
 array([97, 97, 81, 96,  2,  2,  2, 81, 86, 97]),
 array([97, 96, 90, 86, 32, 32, 96, 85, 81, 81]),
 array([ 2, 86, 32, 96, 81, 85,  2,  2, 90, 81]),
 array([86, 85, 96, 32, 97, 81, 81, 81, 86,  5]),
 array([85, 96, 81, 44, 97, 96, 96, 96, 32, 81]),
 array([ 5, 81, 81, 44,  2, 85, 81,  2, 44, 97]),
 array([90, 85, 44, 85,  2,  2,  5, 90, 81, 32]),
 array([32, 97, 81, 81, 85, 97, 81, 81, 81, 32]),
 array([96, 97, 96, 97, 81, 85, 32,  2, 32, 85]),
 array([86, 81,  5, 81, 96, 44, 44, 85,  2, 32]),
 array([90,  2, 90, 97,  2, 90, 44, 44, 32, 44]),
 array([ 2, 32, 96, 85, 32, 90, 86, 32, 81, 44]),
 array([85, 86, 96, 81, 81, 86, 97,  5, 85, 85]),
 array([32, 86, 86,  5, 81, 96, 85, 32, 85, 97]),
 array([86, 85, 96, 96, 90, 81, 81, 90, 97, 96]),
 array([44, 86, 85, 44, 86, 81,  5,  5,  5, 97]),
 array([81, 81, 96, 44, 86, 97, 81,  2, 44, 96]),
